import Image from "next/image";
import CaseStudyShell from "../../components/CaseStudyShell";
import AnimatedStat from "../../components/AnimatedStat";
import {
  ArticleHero,
  ArticleMeta,
  HeroVideo,
  Prose,
  SectionHeader,
} from "../../components/caseStudyUI";
import LightboxFrame from "../../components/LightboxFrame";
import { caseStudyMetadata } from "../../lib/siteMetadata";

export const metadata = caseStudyMetadata({
  title: "Calibrations Ecosystem",
  description:
    "A scalable system that brought structure, trust, and shared context to calibration sessions run inconsistently across the enterprise.",
  slug: "path-360",
});

const LIVE_CALIBRATION_PRINCIPLES = [
  "One consolidated place to view live calibration data, including associate calibration profiles and ratings in a pop-out drawer format.",
  "Drag-and-drop movement so people leaders and facilitators could move associates during live conversation, instead of managing the room manually in Google Sheets.",
  "Distribution data that helped people leaders and session facilitators track each session by percentage and pie chart, making it clear whether the calibration met requirements set by senior org leaders.",
];

const SESSION_PREP_PRINCIPLES = [
  "After a calibration organization was selected, sessions were auto-generated by associate level and job family, a structure used by 87% of calibrations held previously.",
  "We surfaced bulk select, create session, and combine sessions at the top of the page so facilitators could make scheduling changes without editing sessions individually.",
  "A dedicated key-roles area prompted facilitators to assign every required role, something often missed when scheduling sessions in Google Sheets or Calendar.",
  "Facilitators could see whether every associate’s performance one-pager was submitted, confirming the session was ready without chasing individual leaders.",
];

const SESSION_PREP_IMAGES = [
  {
    src: "/case-study/pa-xd/manage1.webp",
    alt: "Session management UI showing a pre-calibration team overview",
    aspect: "1440/1261",
    caption: "Session setup: facilitators could start from a team overview instead of a spreadsheet.",
  },
  {
    src: "/case-study/pa-xd/manage1.1.1.webp",
    alt: "Session management UI showing grouped calibration sessions and setup controls",
    aspect: "1440/1401",
    caption: "Generated sessions: groups, controls, and session details surfaced in one workspace.",
  },
  {
    src: "/case-study/pa-xd/manage2.webp",
    alt: "Session management UI showing rating distribution and calibration prep",
    aspect: "1440/1225",
    caption: "Prep visibility: rating distribution and readiness surfaced before the live conversation.",
  },
  {
    src: "/case-study/pa-xd/manage3.webp",
    alt: "Session management UI showing manager preparation details",
    aspect: "1440/1712",
    caption: "Manager prep: facilitator-facing details made it easier to see who was ready.",
  },
];

function Img({
  src,
  alt,
  aspect = "16/9",
  fit = "cover",
  position = "center",
  sizes = "(max-width: 1024px) 100vw, 1180px",
}: {
  src: string;
  alt: string;
  aspect?: string;
  fit?: "contain" | "cover";
  position?: string;
  sizes?: string;
}) {
  return (
    <LightboxFrame alt={alt}>
      <div className="relative overflow-hidden rounded-xl" style={{ aspectRatio: aspect, background: "var(--card)" }}>
        <Image src={src} alt={alt} fill sizes={sizes} style={{ objectFit: fit, objectPosition: position }} />
      </div>
    </LightboxFrame>
  );
}

function NumberedList({ items }: { items: string[] }) {
  return (
    <div role="list" className="not-prose flex flex-col gap-4">
      {items.map((item, index) => (
        <div role="listitem" key={item} className="flex gap-3.5">
          <span
            className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-[11px] font-semibold"
            style={{ background: "var(--accent-text)", color: "var(--background)" }}
            aria-hidden
          >
            {index + 1}
          </span>
          <span>{item}</span>
        </div>
      ))}
    </div>
  );
}

export default function Path360CaseStudy() {
  return (
    <CaseStudyShell context="Capital One · 2024 – 2025" currentHref="/case-study/path-360">
      <ArticleHero
        eyebrow="Principal Associate, Experience Design · PATH"
        title={
          <>
            Calibration sessions were held inconsistently across the enterprise. I designed a scalable system
            that brought structure, trust, and shared context into the room
            <span style={{ color: "var(--accent)" }}>.</span>
          </>
        }
        meta={
          <ArticleMeta
            role="Lead product designer"
            timeline="Capital One · Dec 2024 – June 2025"
            platform="Enterprise web platform"
            resultsLabel="Directional signal"
            results={[
              { value: "↑ 57%", label: "PLs satisfied with the PM experience" },
              { value: "↑ 70%", label: "PLs confident in final ratings" },
            ]}
          />
        }
      />

      <div className="col-wide">
        <HeroVideo
          src="/case-study/pa-xd/hero2.mp4"
          poster="/case-study/pa-xd/hero2-poster.webp"
          aspect="2288/1320"
          label="Two leaders in a live PATH calibration session, reviewing the distribution matrix and an associate's feedback profile together"
          maxWidth={1260}
        />
        <p className="figure-caption">Live calibration session: two leaders reviewing the distribution matrix and associate feedback profile together.</p>
      </div>

      <SectionHeader index="01" label="The problem" heading="Scaling something human" />
      <Prose>
        <p>
          Calibration is where performance decisions actually get made. Leaders gather, sometimes with a room
          full of peers, to align on ratings, surface standouts, and identify development gaps. It&apos;s high
          stakes, politically charged, and deeply dependent on the quality of information available in the room.
        </p>
        <p>
          We&apos;d proven with the pilot that better feedback inputs led to better calibration conversations. Now we
          needed to build a system that could hold that quality at 70,000-person scale, across business lines,
          seniority levels, and calibration models that looked very different from team to team.
        </p>
        <p>
          My role: lead design for the end-to-end calibration ecosystem within PATH, our performance platform:
          from how sessions are created and managed to what leaders see in the room when decisions are being made.
        </p>
      </Prose>
      <figure className="col-wide">
        <Img src="/case-study/pa-xd/image2.webp" alt="Early whiteboard sessions mapping the end-to-end calibration workflow" aspect="1606/658" fit="cover" />
        <figcaption className="figure-caption">Early whiteboard sessions helped us map the full calibration journey, far messier than the pilot suggested.</figcaption>
      </figure>

      <SectionHeader index="02" label="The users" heading="Who's actually in the room" />
      <Prose>
        <p>
          We started with deep discovery, not just on the calibration session itself, but on all the people moving
          through it. The experience looked radically different depending on whether you were a first-time people
          leader, a senior VP running a large org, or an HR partner facilitating the session.
        </p>
        <p>
          We could have designed one calibration screen for &ldquo;the user.&rdquo; But calibration isn&apos;t one job. A
          people leader defending ratings, an HRBP coaching that leader, and a facilitator keeping the room fair
          each want different things from the same screen. So we split into three personas instead of averaging
          them into one, then narrowed scope to what a single MVP could actually serve.
        </p>
      </Prose>
      <figure className="col-wide">
        <Img src="/case-study/pa-xd/image2.5-clean.webp" alt="The three calibration personas: people leaders, PM champs / HRBPs, and facilitators, and what each needs" aspect="1756/608" fit="contain" />
        <figcaption className="figure-caption">Three personas, three different needs: from a single consistent prep space to flexible tools for editing ratings.</figcaption>
      </figure>
      <Prose>
        <p>
          Once the personas were clear, we mapped each job-to-be-done across the calibration phases: prep, live
          calibration, and post-calibration. That helped us decide which capabilities belonged in the first
          release and which needed to be descoped, so the MVP could focus on the moments where better structure
          would change the quality of the session.
        </p>
      </Prose>
      <figure className="col-wide">
        <Img src="/case-study/pa-xd/image3.webp" alt="Persona journey map: people leaders, HRBPs, and facilitators across prep, live, and post calibration" aspect="1558/632" fit="cover" />
        <figcaption className="figure-caption">Personas mapped across the calibration journey: each role&apos;s jobs-to-be-done at every phase.</figcaption>
      </figure>

      <SectionHeader index="03" label="The prep" heading="Before the room: Prep for calibrations" />
      <Prose>
        <p>
          Before PATH, calibration sessions were set up manually by HR business partners in Google Sheets. Each
          group had to be assembled by hand: which teams should calibrate together, which associates belonged in
          each session, who needed to attend, and when the conversation should happen.
        </p>
        <p>
          We created a smarter setup system that let HR partners select the teams they wanted to calibrate
          together, then automatically generated session groups by level and job family. From there, they could
          edit the details that still needed human judgment: attendees, calibrated associates, session timing,
          and any edge cases before the room began.
        </p>
        <NumberedList items={SESSION_PREP_PRINCIPLES} />
      </Prose>
      <figure className="col-wide grid grid-cols-1 items-start gap-6">
        {SESSION_PREP_IMAGES.map((image) => (
          <figure key={image.src}>
            <Img src={image.src} alt={image.alt} aspect={image.aspect} fit="contain" sizes="(max-width: 768px) 100vw, min(50vw, 620px)" />
            <figcaption className="figure-caption">{image.caption}</figcaption>
          </figure>
        ))}
      </figure>

      <SectionHeader index="04" label="The live calibration" heading="In the room: live calibrations" />
      <Prose>
        <p>
          Live calibrations are the hard part. We built this experience for two core personas: people leaders
          making talent decisions and facilitators responsible for keeping the session structured, fair, and
          moving. The room has multiple leaders, one shared screen, limited time, and years of performance data
          that need to resolve into actionable decisions.
        </p>
        <p>
          The distribution view gave rooms a shared anchor. The individual view surfaced 360 feedback alongside
          performance data, so leaders could have real conversations instead of debating from memory. Status
          tracking let sessions pause and resume without losing ground.
        </p>
        <NumberedList items={LIVE_CALIBRATION_PRINCIPLES} />
      </Prose>
      <figure className="col-wide grid grid-cols-1 gap-y-8">
        <figure>
          <Img src="/case-study/pa-xd/04-2.webp" alt="Live calibration UI showing an individual associate deep-dive panel" aspect="1440/1779" fit="contain" />
          <figcaption className="figure-caption">Associate deep-dive: evidence and calibration context opened without leaving the live room.</figcaption>
        </figure>
        <figure>
          <Img src="/case-study/pa-xd/04-3.webp" alt="Live calibration UI showing 360 feedback surfaced during a session" aspect="1440/1779" fit="contain" />
          <figcaption className="figure-caption">360 feedback in session: qualitative evidence stayed visible while leaders made rating decisions.</figcaption>
        </figure>
      </figure>

      <SectionHeader index="05" label="The field signal" heading="Early signal from the field" />
      <Prose>
        <p>
          We ran iterative research throughout the build, not just usability studies, but ongoing conversations
          with people leaders and HR partners as the experience took shape. The early feedback validated our core
          bets and surfaced edge cases we hadn&apos;t anticipated.
        </p>
        <p>
          Once this experience launched, leaders described calibrations as feeling &ldquo;more grounded&rdquo;: less
          debate about facts, more real conversation about development. HR partners noted fewer escalations
          post-session. The signal was clear enough to accelerate the enterprise rollout.
        </p>
      </Prose>
      <figure className="col-wide">
        <Img src="/case-study/pa-xd/group12.png" alt="Early feedback from the field: leader and HR partner testimonials from the pilot" aspect="1667/871" fit="cover" />
        <figcaption className="figure-caption">Early feedback from the field: leaders felt more prepared, conversations felt more fair.</figcaption>
      </figure>

      <SectionHeader index="06" label="The outcome" heading="From pilot to platform" />
      <Prose>
        <p>
          PATH launched as Capital One&apos;s first enterprise performance management platform, built on the
          foundation the pilot established. The calibration ecosystem was the next main addition to the platform
          alongside the 360 feedback experience.
        </p>
      </Prose>
      <div className="col-wide grid grid-cols-1 gap-[2px] sm:grid-cols-3">
        {[
          { value: "4 out of 5", label: "Calibration sessions reported fewer disputes and stronger post-session alignment" },
          { value: "↑ 70,000+", label: "employees across Capital One, scaled from an 800-person pilot" },
          { value: "86%", label: "HR partners reported reduced escalations and cleaner outcomes in sessions using PATH" },
        ].map((outcome) => (
          <div key={outcome.label} className="flex flex-col justify-center gap-2 rounded-xl px-5 sm:px-6 py-4" style={{ background: "var(--card)" }}>
            <p className="m-0 font-semibold tabular-nums" style={{ fontSize: "clamp(30px, 4vw, 46px)", letterSpacing: "-0.03em", lineHeight: 1, color: "var(--pop)" }}>
              <AnimatedStat value={outcome.value} />
            </p>
            <p className="m-0 text-[13px] sm:text-[14px] leading-relaxed" style={{ color: "var(--body)" }}>{outcome.label}</p>
          </div>
        ))}
      </div>
      <p className="col-wide mono-label">Directional figures from the pilot and early rollout; the 70,000+ reflects full enterprise scale.</p>

      <SectionHeader index="07" label="The reflection" heading="What enterprise scale taught me" />
      <Prose>
        <p>
          Building this ecosystem taught me what it means to design at enterprise scale, where the system has to
          hold for every edge case, not just the happy path.
        </p>
        <p>
          The work that mattered most wasn&apos;t the interface. It was the alignment work: getting HR, engineering,
          product, and business stakeholders onto the same model of what calibration should do and for whom.
          Design was the medium for that conversation.
        </p>
        <p>
          I also learned that launching isn&apos;t the end. The most valuable research happened after PATH was in the
          field, when real users surfaced problems we never would have caught in a lab.
        </p>
      </Prose>
    </CaseStudyShell>
  );
}
