import Image from "next/image";
import Link from "next/link";
import { FONT } from "../../components/ui";
import AnimatedStat from "../../components/AnimatedStat";
import { IntroMetadataSection } from "../../components/caseStudyUI";
import LightboxFrame from "../../components/LightboxFrame";
import { NextProjectCard, NextProjectLink } from "../../components/ProjectNavigation";
import { caseStudyMetadata } from "../../lib/siteMetadata";

export const metadata = caseStudyMetadata({
  title: "Calibrations Ecosystem",
  description:
    "A scalable system that brought structure, trust, and shared context to calibration sessions run inconsistently across the enterprise.",
  slug: "path-360",
});

const PROSE = "prose font-light leading-[1.8] text-[16px] sm:text-[18px]";
const LABEL = "text-[10px] tracking-[0.28em] uppercase";
const SECTION_HEADING = { fontSize: "clamp(20px, 2.2vw, 28px)", letterSpacing: "-0.02em", lineHeight: 1.25 };
const LIVE_CALIBRATION_PRINCIPLES = [
  "One consolidated place to view live calibration data, including associate calibration profiles and ratings in a pop-out drawer format.",
  "Drag-and-drop movement so people leaders and facilitators could move associates during live conversation, instead of managing the room manually in Google Sheets.",
  "Distribution data that helped people leaders and session facilitators track each session by percentage and pie chart, making it clear whether the calibration met requirements set by senior org leaders.",
];
const SESSION_PREP_PRINCIPLES = [
  "After a calibration organization was selected, sessions were auto-generated by associate level and job family, a structure used by 87% of calibrations held previously.",
  "We surfaced bulk select, create session, and combine sessions at the top of the page so facilitators could make scheduling changes without editing sessions individually.",
  "A dedicated key-roles area prompted facilitators to assign every required role, something often missed when scheduling sessions in Google Sheets or Calendar.",
  "Facilitators could see whether every associate’s performance one-pager was submitted, confirming the session was ready without chasing individual leaders.",
];
function Img({ src, alt, aspect = "16/9", fit = "cover", position = "center" }: { src: string; alt: string; aspect?: string; fit?: "contain" | "cover"; position?: string }) {
  return (
    <LightboxFrame alt={alt}>
      <div
        className="relative overflow-hidden rounded-xl"
        style={{ aspectRatio: aspect, background: "var(--card)" }}
      >
        <Image src={src} alt={alt} fill sizes="(max-width: 1024px) 100vw, 1180px" style={{ objectFit: fit, objectPosition: position }} />
      </div>
    </LightboxFrame>
  );
}

export default function Path360CaseStudy() {
  return (
    <main style={{ background: "var(--background)", color: "var(--foreground)", ...FONT }}>

      {/* ── Top bar ── */}
      <div className="sticky top-0 z-40 border-b border-[var(--border)]" style={{ backgroundColor: "var(--card)" }}>
        <div className="max-w-[1260px] mx-auto px-6 sm:px-10 h-12 flex items-center justify-between">
          <Link href="/" className="text-[11px] font-normal tracking-[0.15em] uppercase text-[var(--midtone)] hover:text-[var(--foreground)] transition-colors duration-200">← Back</Link>
          <span className="hidden text-[11px] font-normal tracking-[0.15em] uppercase text-[var(--midtone)] md:inline">Capital One · 2024 – 2025</span>
          <NextProjectLink currentHref="/case-study/path-360" />
        </div>
      </div>

      {/* ── Hero text ── */}
      <div className="max-w-[1260px] mx-auto px-6 sm:px-10 pt-16 pb-12 flex flex-col gap-6">
        <p className={`${LABEL} text-[var(--accent-text)]`}>Principal Associate, Experience Design · PATH</p>
        <h1 className="font-light max-w-[1100px]" style={{ fontSize: "clamp(32px, calc(5vw - 2px), 52px)", letterSpacing: "-0.03em", lineHeight: 1.14 }}>
          Calibration sessions were held inconsistently across the enterprise. I designed a scalable system that brought structure, trust, and shared context into the room<span style={{ color: "var(--accent)" }}>.</span>
        </h1>
        <IntroMetadataSection
          role="Lead product designer"
          timeline="Capital One · Dec 2024 – June 2025"
          platform="Enterprise web platform"
          resultsLabel="Directional signal"
          results={[
            { value: "↑ 57%", label: "PLs satisfied with the PM experience" },
            { value: "↑ 70%", label: "PLs confident in final ratings" },
          ]}
        />
      </div>

      {/* ── Hero image ── */}
      <div className="max-w-[1260px] mx-auto px-6 sm:px-10 pb-0">
        <Img
          src="/case-study/pa-xd/hero-editorial.webp"
          alt="Two leaders in a live PATH calibration session, reviewing the distribution matrix and an associate's feedback profile together"
          aspect="1137/928"
          fit="cover"
        />
      </div>

      {/* ── The Problem ── */}
      <div className="max-w-[1260px] mx-auto px-6 sm:px-10">
        <section className="py-16 flex flex-col gap-10">
          <div className="flex flex-col gap-5 md:grid md:grid-cols-[1fr_2fr] md:gap-16">
            <div className="flex flex-col gap-2">
              <p className={`${LABEL} text-[var(--accent-text)]`}>The problem</p>
              <h2 className="font-light" style={SECTION_HEADING}>Scaling something human</h2>
            </div>
            <div className="flex flex-col gap-8">
              <div className={`${PROSE}`} style={{ color: "var(--body)" }}>
                <p>Calibration is where performance decisions actually get made. Leaders gather, sometimes with a room full of peers, to align on ratings, surface standouts, and identify development gaps. It's high stakes, politically charged, and deeply dependent on the quality of information available in the room.</p>
                <p>We'd proven with the pilot that better feedback inputs led to better calibration conversations. Now we needed to build a system that could hold that quality at 70,000-person scale, across business lines, seniority levels, and calibration models that looked very different from team to team.</p>
                <p>My role: lead design for the end-to-end calibration ecosystem within PATH, our performance platform: from how sessions are created and managed to what leaders see in the room when decisions are being made.</p>
              </div>
            </div>
          </div>

          <figure className="flex flex-col gap-3">
            <Img src="/case-study/pa-xd/image2.webp" alt="Early whiteboard sessions mapping the end-to-end calibration workflow" aspect="1606/658" fit="cover" />
            <figcaption className="text-[10px] font-light text-[var(--midtone)] tracking-wide">Early whiteboard sessions helped us map the full calibration journey, far messier than the pilot suggested.</figcaption>
          </figure>
        </section>

        {/* ── Discovery ── */}
        <section className="py-16 flex flex-col gap-10">
          <div className="flex flex-col gap-5 md:grid md:grid-cols-[1fr_2fr] md:gap-16">
            <div className="flex flex-col gap-2">
              <p className={`${LABEL} text-[var(--accent-text)]`}>01</p>
              <h2 className="font-light" style={SECTION_HEADING}>Who's actually in the room</h2>
            </div>
            <div className={`${PROSE}`} style={{ color: "var(--body)" }}>
              <p>We started with deep discovery, not just on the calibration session itself, but on all the people moving through it. The experience looked radically different depending on whether you were a first-time people leader, a senior VP running a large org, or an HR partner facilitating the session.</p>
              <p>We could have designed one calibration screen for &ldquo;the user.&rdquo; But calibration isn&apos;t one job. A people leader defending ratings, an HRBP coaching that leader, and a facilitator keeping the room fair each want different things from the same screen. So we split into three personas instead of averaging them into one, then narrowed scope to what a single MVP could actually serve.</p>
            </div>
          </div>

          <figure className="flex flex-col gap-2">
            <Img src="/case-study/pa-xd/image2.5-clean.webp" alt="The three calibration personas: people leaders, PM champs / HRBPs, and facilitators, and what each needs" aspect="1756/608" fit="contain" />
            <figcaption className="text-[10px] font-light text-[var(--midtone)] tracking-wide">Three personas, three different needs: from a single consistent prep space to flexible tools for editing ratings</figcaption>
          </figure>

          <div className={`${PROSE}`} style={{ color: "var(--body)" }}>
            <p>Once the personas were clear, we mapped each job-to-be-done across the calibration phases: prep, live calibration, and post-calibration. That helped us decide which capabilities belonged in the first release and which needed to be descoped, so the MVP could focus on the moments where better structure would change the quality of the session.</p>
          </div>

          <figure className="flex flex-col gap-2">
            <Img src="/case-study/pa-xd/image3.webp" alt="Persona journey map: people leaders, HRBPs, and facilitators across prep, live, and post calibration" aspect="1558/632" fit="cover" />
            <figcaption className="text-[10px] font-light text-[var(--midtone)] tracking-wide">Personas mapped across the calibration journey: each role's jobs-to-be-done at every phase</figcaption>
          </figure>
        </section>

        {/* ── Designing the System ── */}
        <section className="py-16 flex flex-col gap-10">
          <div className="flex flex-col gap-5 md:grid md:grid-cols-[1fr_2fr] md:gap-16">
            <div className="flex flex-col gap-2">
              <p className={`${LABEL} text-[var(--accent-text)]`}>02</p>
              <h2 className="font-light" style={SECTION_HEADING}>Before the room: Prep for calibrations</h2>
            </div>
            <div className={`${PROSE}`} style={{ color: "var(--body)" }}>
              <p>Before PATH, calibration sessions were set up manually by HR business partners in Google Sheets. Each group had to be assembled by hand: which teams should calibrate together, which associates belonged in each session, who needed to attend, and when the conversation should happen.</p>
              <p>We created a smarter setup system that let HR partners select the teams they wanted to calibrate together, then automatically generated session groups by level and job family. From there, they could edit the details that still needed human judgment: attendees, calibrated associates, session timing, and any edge cases before the room began.</p>
            </div>
          </div>

          <figure className="flex flex-col gap-8">
            <div className="flex flex-col gap-2">
              <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
                {SESSION_PREP_PRINCIPLES.slice(0, 2).map((principle, index) => (
                  <div
                    key={principle}
                    className="flex items-start gap-3 rounded-xl px-4 py-3"
                    style={{ background: "var(--card)" }}
                  >
                    <span
                      className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-[10px] font-semibold"
                      style={{ background: "var(--accent-text)", color: "var(--background)" }}
                    >
                      {index + 1}
                    </span>
                    <p className="m-0 text-[12px] leading-relaxed" style={{ color: "var(--body)" }}>{principle}</p>
                  </div>
                ))}
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                <Img src="/case-study/pa-xd/manage1.webp" alt="Session management UI showing a pre-calibration team overview" aspect="1440/1261" fit="contain" />
                <Img
                  src="/case-study/pa-xd/manage1.1.1.webp"
                  alt="Session management UI showing grouped calibration sessions and setup controls"
                  aspect="1440/1401"
                  fit="contain"
                />
              </div>
            </div>
            <div className="flex flex-col gap-2">
              <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
                {SESSION_PREP_PRINCIPLES.slice(2, 4).map((principle, index) => (
                  <div
                    key={principle}
                    className="flex items-start gap-3 rounded-xl px-4 py-3"
                    style={{ background: "var(--card)" }}
                  >
                    <span
                      className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-[10px] font-semibold"
                      style={{ background: "var(--accent-text)", color: "var(--background)" }}
                    >
                      {index + 3}
                    </span>
                    <p className="m-0 text-[12px] leading-relaxed" style={{ color: "var(--body)" }}>{principle}</p>
                  </div>
                ))}
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                <Img
                  src="/case-study/pa-xd/manage2.webp"
                  alt="Session management UI showing rating distribution and calibration prep"
                  aspect="1440/1225"
                  fit="contain"
                />
                <Img
                  src="/case-study/pa-xd/manage3.webp"
                  alt="Session management UI showing manager preparation details"
                  aspect="1440/1712"
                  fit="contain"
                />
              </div>
            </div>
          </figure>
        </section>

        {/* ── Live Calibrations ── */}
        <section className="py-16 flex flex-col gap-10">
          <div className="flex flex-col gap-5 md:grid md:grid-cols-[1fr_2fr] md:gap-16">
            <div className="flex flex-col gap-2">
              <p className={`${LABEL} text-[var(--accent-text)]`}>03</p>
              <h2 className="font-light" style={SECTION_HEADING}>In the room: live calibrations</h2>
            </div>
            <div className={`${PROSE}`} style={{ color: "var(--body)" }}>
              <p>Live calibrations are the hard part. We built this experience for two core personas: people leaders making talent decisions and facilitators responsible for keeping the session structured, fair, and moving. The room has multiple leaders, one shared screen, limited time, and years of performance data that need to resolve into actionable decisions.</p>
            </div>
          </div>

          <figure className="flex flex-col gap-3">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-x-3 gap-y-8">
              <div className="md:col-span-2">
                <Img src="/case-study/pa-xd/image4.1.webp" alt="Live calibration UI showing session management, rating distribution, and prep experience" aspect="1582/706" fit="cover" />
              </div>
              <p className="md:col-span-2 text-[16px] sm:text-[18px] font-light leading-[1.8] py-2" style={{ color: "var(--body)" }}>
                The distribution view gave rooms a shared anchor. The individual view surfaced 360 feedback alongside performance data, so leaders could have real conversations instead of debating from memory. Status tracking let sessions pause and resume without losing ground.
              </p>
              <div className="grid grid-cols-1 gap-2 md:col-span-2 sm:grid-cols-2">
                {LIVE_CALIBRATION_PRINCIPLES.map((principle, index) => (
                  <div
                    key={principle}
                    className={`flex items-start gap-3 rounded-xl px-4 py-3 ${index === 2 ? "sm:col-span-2" : ""}`}
                    style={{ background: "var(--card)" }}
                  >
                    <span
                      className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-[10px] font-semibold"
                      style={{ background: "var(--accent-text)", color: "var(--background)" }}
                    >
                      {index + 1}
                    </span>
                    <p className="m-0 text-[12px] leading-relaxed" style={{ color: "var(--body)" }}>{principle}</p>
                  </div>
                ))}
              </div>
              <Img
                src="/case-study/pa-xd/04-2.webp"
                alt="Live calibration UI showing an individual associate deep-dive panel"
                aspect="1440/1779"
                fit="contain"
              />
              <Img
                src="/case-study/pa-xd/04-3.webp"
                alt="Live calibration UI showing 360 feedback surfaced during a session"
                aspect="1440/1779"
                fit="contain"
              />
            </div>
          </figure>
        </section>
      </div>

      {/* ── Feedback + Scale ── */}
      <div className="max-w-[1260px] mx-auto px-6 sm:px-10">
        <section className="py-16 flex flex-col gap-10">
          <div className="flex flex-col gap-5 md:grid md:grid-cols-[1fr_2fr] md:gap-16">
            <div className="flex flex-col gap-2">
              <p className={`${LABEL} text-[var(--accent-text)]`}>04</p>
              <h2 className="font-light" style={SECTION_HEADING}>Early signal from the field</h2>
            </div>
            <div className={`${PROSE}`} style={{ color: "var(--body)" }}>
              <p>We ran iterative research throughout the build, not just usability studies, but ongoing conversations with people leaders and HR partners as the experience took shape. The early feedback validated our core bets and surfaced edge cases we hadn't anticipated.</p>
              <p>Once this experience launched, leaders described calibrations as feeling "more grounded": less debate about facts, more real conversation about development. HR partners noted fewer escalations post-session. The signal was clear enough to accelerate the enterprise rollout.</p>
            </div>
          </div>

          <figure className="flex flex-col gap-3">
            <Img src="/case-study/pa-xd/image-last2.webp" alt="Early feedback from the field: leader and HR partner testimonials from the pilot" aspect="1667/871" fit="cover" />
            <figcaption className="text-[10px] font-light text-[var(--midtone)] tracking-wide">Early feedback from the field: leaders felt more prepared, conversations felt more fair</figcaption>
          </figure>
        </section>
      </div>

      {/* ── Outcome + Growth ── */}
      <div className="max-w-[1260px] mx-auto px-6 sm:px-10">
        <section className="py-16 flex flex-col gap-10">
          <div className="flex flex-col gap-5 md:grid md:grid-cols-[1fr_2fr] md:gap-16">
            <div className="flex flex-col gap-2">
              <p className={`${LABEL} text-[var(--accent-text)]`}>Outcome</p>
              <h2 className="font-light" style={SECTION_HEADING}>From pilot to platform</h2>
            </div>
            <div className={`${PROSE}`} style={{ color: "var(--body)" }}>
              <p>PATH launched as Capital One&apos;s first enterprise performance management platform, built on the foundation the pilot established. The calibration ecosystem was the next main addition to the platform alongside the 360 feedback experience.</p>
            </div>
          </div>
          <div className="grid grid-cols-1 gap-[2px] sm:grid-cols-3">
            {[
              { value: "4 out of 5", label: "Calibration sessions reported fewer disputes and stronger post-session alignment" },
              { value: "↑ 70,000+", label: "employees across Capital One, scaled from an 800-person pilot" },
              { value: "86%", label: "HR partners reported reduced escalations and cleaner outcomes in sessions using PATH" },
            ].map((outcome) => (
              <div
                key={outcome.label}
                className="flex flex-col justify-center gap-2 rounded-xl px-5 sm:px-6 py-4"
                style={{ background: "var(--card)" }}
              >
                {outcome.value && (
                  <p className="m-0 font-semibold tabular-nums" style={{ fontSize: "clamp(30px, 4vw, 46px)", letterSpacing: "-0.03em", lineHeight: 1, color: "var(--pop)" }}>
                    <AnimatedStat value={outcome.value} />
                  </p>
                )}
                <p className="m-0 text-[13px] sm:text-[14px] leading-relaxed" style={{ color: "var(--body)" }}>{outcome.label}</p>
              </div>
            ))}
          </div>
          <p className="text-[10px] font-light text-[var(--midtone)] tracking-wide">
            Directional figures from the pilot and early rollout; the 70,000+ reflects full enterprise scale.
          </p>
        </section>

        {/* ── Growth ── */}
        <section className="py-16 flex flex-col gap-10">
          <div className="flex flex-col gap-5 md:grid md:grid-cols-[1fr_2fr] md:gap-16">
            <div className="flex flex-col gap-2">
              <p className={`${LABEL} text-[var(--accent-text)]`}>What I learned</p>
              <h2 className="font-light" style={SECTION_HEADING}>What enterprise scale taught me</h2>
            </div>
            <div className={`${PROSE}`} style={{ color: "var(--body)" }}>
              <p>Building this ecosystem taught me what it means to design at enterprise scale, where the system has to hold for every edge case, not just the happy path.</p>
              <p>The work that mattered most wasn't the interface. It was the alignment work: getting HR, engineering, product, and business stakeholders onto the same model of what calibration should do and for whom. Design was the medium for that conversation.</p>
              <p>I also learned that launching isn't the end. The most valuable research happened after PATH was in the field, when real users surfaced problems we never would have caught in a lab.</p>
            </div>
          </div>
        </section>

        <NextProjectCard currentHref="/case-study/path-360" />

        {/* ── Footer ── */}
        <footer className="py-10 flex flex-wrap items-center justify-between gap-2">
          <p className="text-[10px] font-light text-[var(--midtone)] tracking-wide">© 2026 Niharika Mishra</p>
          <Link href="/" className="text-[11px] font-normal tracking-[0.2em] uppercase text-[var(--midtone)] hover:text-[var(--foreground)] border-b border-[var(--border)] pb-0.5 hover:border-[var(--foreground)] transition-colors duration-200">
            ← Back to portfolio
          </Link>
        </footer>
      </div>
    </main>
  );
}
